apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-api-deployment
spec:
  selector:
    matchLabels:
      app: cat-api
  template:
    metadata:
      labels:
        app: cat-api
    spec:
      containers:
      - name: cat-api
        image: cat-api
        # resources:
        #   requests:
        #     memory: "32Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3000

